Percentage
gillout/calculator pull request #5
Opened 2020-10-20 17:15 UTC by gillout

2020-10-20 22:58 UTC, matthieuaudemard requested changes
Simple et efficace ;) . Juste 1 petite erreur et une petite opti à corriger et tu peux merge ;)

2020-10-20 22:58 UTC, matthieuaudemard commented on app/model/CalculatorManager.php
> +        $result = (floatval($this->calc->getAccumulator())) * 1 / 100;
tu peux simplifier `* 1 / 100` en `/ 100`, c'est un tout p'tit peu plus opti ;)

2020-10-20 22:58 UTC, matthieuaudemard commented on app/controller/AppController.php
> +                    $this->manager->percentage();
Il manque un break ici. Si tu avais mis quelque chose dans le `default` il serait executé juste après le `case 'percnt':`.

2020-10-21 08:27 UTC, gillout commented on app/model/CalculatorManager.php
> +        $result = (floatval($this->calc->getAccumulator())) * 1 / 100;
Oui, c'est vrai j'aurais du le voir.

2020-10-21 08:27 UTC, gillout commented on app/controller/AppController.php
> +                    $this->manager->percentage();
Sacrilège, j'ai oublié le break. rooooo

2020-10-21 08:28 UTC, merged