Feat : Gestion du clic sur le bouton "&plusmn;"
gillout/calculator pull request #8
Opened 2020-11-10 23:07 UTC by gillout

2020-11-11 13:30 UTC, matthieuaudemard requested changes
Un petit bug à corriger 😉

2020-11-11 13:30 UTC, matthieuaudemard commented on app/model/CalculatorManager.php
> +            $this->calc->setAccumulator(str_replace('-', '', $accumulator));
Ok ça me parait bien mais j'ai testé en local et j'ai touvé un bug (cf : issue https://github.com/gillout/calculator/issues/9)

2020-11-11 18:32 UTC, matthieuaudemard requested changes
Le problème du signe n'est tjs pas résolu. Le scénario est le suivant :
- Faire '+/-' sur 0
- Taper n'importe quel chiffre par la suite
- le signe redevient positif

2020-11-11 18:32 UTC, matthieuaudemard commented on app/model/CalculatorManager.php
> +            throw new Exception('0 ne peut pas être négatif');
Alors en fait si, 0 peut être négatif. Le problème c'est que quand tu met 0 en négatif et que tu tapes par exemple '3', on s'attend à avoir -3 or on a 3.

2020-11-11 20:56 UTC, gillout commented on app/model/CalculatorManager.php
> +            throw new Exception('0 ne peut pas être négatif');
Je ne suis pas d'accord là dessus.
Sur 0 si tu fais +- cela ne doit rien faire.
Ce signe se met après avoir taper un chiffre ou nombre et non avant donc tu ne peux pas mettre le - avec le bouton +- et ensuite taper un nombre en espérant l'avoir en négatif.
Tu peux vérifier sur d'autres calculatrices. ;)

2020-11-11 20:57 UTC, gillout commented on app/model/CalculatorManager.php
> +            throw new Exception('0 ne peut pas être négatif');
Pour le message d'erreur par contre, oui, on peut le changer.

2020-11-12 07:43 UTC, gillout commented on app/model/CalculatorManager.php
> +            throw new Exception('0 ne peut pas être négatif');
J'ai regardé sur celle de ma femme :
Elle prend le signe "-" s'il y a 0 mais ensuite l'enlève si tu tapes un chiffre.

2020-11-12 07:44 UTC, gillout commented on app/model/CalculatorManager.php
> +            throw new Exception('0 ne peut pas être négatif');
Sur celle de Windows, le zéro ne prends pas le signe "-".

2020-11-12 18:11 UTC, matthieuaudemard approved these changes

2020-11-12 18:15 UTC, merged